services:

  upload_server:
    build: ./flask
    container_name: upload_server
    restart: no
    env_file:
      - ./config/.env
    environment:
      # can be development or production
      - ENV=development
    volumes:
      - ./uploads:/app/uploads:rw
      # For development:
      - ./flask/app:/app/app:rw
    expose:
      - 8080
    # For development:
    ports:
      - 5000:5000

  # Dont need nginx for development
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
